using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Football
{
    class DraftClasses
    {
        private int curr;
        public DraftClasses()
        {
            curr = 0;
        }
        public List<Player> GetNextClass()
        {
            List<Player> retVal = null;
            switch(curr)
            {
                case 0:                    
                    retVal = FirstClass();
                    break;
            }
            curr++;
            /*if(retVal != null)
            {
                Dictionary<CollegeList, int> dict = new Dictionary<CollegeList, int>();
                foreach(Player p in retVal)
                {
                    if (dict.ContainsKey(p.GetCollege())) 
                    { 
                        dict[p.GetCollege()]++;
                    }
                    else
                    {
                        dict.Add(p.GetCollege(), 1);
                    }
                }
                Console.WriteLine("TEST");
            }*/
            return retVal;
        }
        private List<Player> FirstClass()
        {
            List<Player> players = new List<Player>();
            players.Add(PlayerFactory.GeneratePlayer("QB/Nick Williams/Marshall/73/207/Pocket/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Casey Wynn/UTSA/73/242/Balanced/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/David Foster/Navy/75/207/Scrambler/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Jason Robinson/Tennessee/76/219/Scrambler/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Kellen Archie/Georgia_Tech/72/216/Scrambler/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Brian Jackson/UConn/75/206/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Deon Johnson/Stanford/73/202/Pocket/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Chris Roberts/West_Virginia/75/226/Pocket/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Will Cummings/Florida/72/222/Scrambler/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Martin Dean/Texas/77/228/Pocket/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Hunter Maxwell/UCF/71/216/Pocket/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Danny White/Northwestern/74/229/Scrambler/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Barrett Martin/UTEP/71/178/Scrambler/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("QB/Derrick Miler/Alabama/73/204/Pocket/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Lawrence Grant/Marshall/71/237/Power/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Eric Ivey/Rice/72/201/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Steve Kenney/Wisconsin/69/182/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/David Romero/Alabama/73/251/Power/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Jayson Wilcox/Marshall/73/201/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/David Stevenson/Pitt/74/215/Speed/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Terrence Jones/LSU/69/181/Speed/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/J.P. Darby/Florida_State/73/218/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Cody Dean/Florida_State/72/219/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Eddie Long/Michigan/72/209/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Derek Allen/USC/71/217/Power/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Albert Johnson/West_Virginia/72/208/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Caleb Wilson/Florida/74/220/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Melvin Ingram/UL_Lafayette/73/251/Power/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/John Griffin/Penn_State/73/213/Speed/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Sam Walker/Oklahoma_State/69/219/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/John Sullivan/TCU/73/216/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Julius Taylor/UCLA/72/195/Balanced/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("RB/Mike Hopkins/Wake_Forest/72/205/Speed/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("RB/James Kemp/Illinois/70/196/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("FB/Justin Bailey/Kentucky/71/231/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("FB/Ronnie Robinson/Arkansas/72/255/Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("FB/Jon Bryant/Penn_State/73/229/Receiving/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Quinton Brown/UTSA/74/190/Speed/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Nathan Hardy/UTSA/74/188/Balanced/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Tony Allen/Georgia/72/202/Balanced/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Patrick Ralph/Ohio_State/69/203/Speed/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Danny Ross/Texas/79/219/Red Zone Threat/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Ken Hall/USF/73/209/Possession/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Brad Johnson/Georgia/72/184/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Brandon Gold/Oregon/74/205/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Travis Kemp/TCU/78/228/Red Zone Threat/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Dan Joseph/Georgia/75/200/Possession/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Josh Carter/Florida_State/75/199/Possession/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Wesley Alvarez/Notre_Dame/75/208/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Jonathon Williamson/Oklahoma/72/212/Possession/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Jeff Thompson/Wake_Forest/76/226/Possession/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Alex Lewis/Mississippi_State/71/199/Possession/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Terry Bell/Penn_State/74/224/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Damien Cutler/South_Carolina/71/195/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Cored Goodman/Texas/76/230/Possession/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Tye Harrison/USC/72/177/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Manuel Lindsey/Baylor/72/207/Possession/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Martin Martinez/Illinois/72/216/Speed/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Carey Cunningham/Alabama/72/198/Balanced/Below Average/21"));
            players.Add(PlayerFactory.GeneratePlayer("WR/J.J. Wilson/Oregon/71/199/Possession/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Damon Parker/Penn_State/76/209/Red Zone Threat/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Barrett Richards/Penn_State/71/192/Speed/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/John Bernard/Stanford/72/185/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Herb Carrington/South_Carolina/75/201/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/James Moore/ECU/74/192/Possession/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Eric Collins/Mississippi_State/73/220/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Chris West/Ohio_State/75/205/Balanced/Bad/21"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Erik Franklin/Northern_Illinois/70/191/Speed/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Amir Atkins/Northwestern/71/200/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Jason Ford/Oregon/72/214/Balanced/Bad/21"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Charlie Bennett/Virginia_Tech/71/209/Possession/Bad/21"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Josh Quinn/Boise_State/72/213/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("WR/Andrew Ross/Miami_FL/74/211/Speed/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Mark Armstrong/Alabama/79/242/Receiving/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Chad Smith/Stanford/79/245/Blocking/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/John Ruffin/ECU/79/257/Receiving/Great/21"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Clarence Sanders/Marshall/77/258/Blocking/Good/21"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Phil Baker/Indiana/76/258/Blocking/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Charles Fowlkes/Alabama/78/252/Receiving/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/DeMarcus Weatherford/South_Carolina/75/227/Receiving/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/John Benson/Clemson/76/260/Blocking/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Andrew Stewart/Texas/76/236/Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Clarence Roberts/Troy/76/265/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Jerome Jackson/Cal/78/233/Blocking/Below Average/21"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Shawn Hayden/Iowa/77/244/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Kevin McNamara/Temple/78/253/Receiving/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/David Austin/Toledo/77/263/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Micah Gray/Kentucky/73/237/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Ken Pennington/Mississippi_State/74/248/Blocking/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/James Whitaker/Oregon/77/229/Receiving/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Eddie Stewart/Purdue/75/233/Receiving/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Brandon Royal/Syracuse/75/233/Blocking/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Kyle Peters/Tennessee/75/262/Receiving/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/J.J. Jackson/UNLV/77/274/Receiving/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("TE/Anthony Alexander/UTEP/74/268/Balanced/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Justin Bergstrand/Louisiana_Tech/76/298/Pass Blocking/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Chad Ralph/Alabama/79/302/Run Blocking/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Shaun Davis/ECU/77/293/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Matt Jones/South_Carolina/74/291/Pass Blocking/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Clayton Simon/Northern_Illinois/75/278/Run Blocking/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Luke Sampson/Penn_State/80/334/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Thomas Williams/Auburn/77/284/Run Blocking/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Marcus Goins/LSU/79/308/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Chase Keyes/Florida_State/78/275/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Tony Bridges/Michigan/77/318/Pass Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Isiah Jones/USC/78/326/Pass Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Adam Nunez/Florida/76/304/Pass Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Curtis Murray/Georgia/79/283/Pass Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Roy Means/Florida_State/74/265/Run Blocking/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Adam East/Georgia/77/279/Pass Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Thomas White/Navy/78/283/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Ron Wheeler/Arizona/76/306/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Dustin Malone/UNLV/80/330/Pass Blocking/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Jayson Dawson/Wisconsin/73/317/Pass Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Ryan Berry/Wisconsin/77/294/Run Blocking/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/David Thompson/Arizona_State/77/312/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/John Leierer/Mississippi_State/75/301/Run Blocking/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Levi Baker/North_Carolina/80/317/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Ken Dukes/Clemson/76/304/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("T/Calvin Pitts/Mississippi_State/78/303/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Marcus Love/Penn_State/80/325/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Carl Lawson/Alabama/76/297/Run Blocking/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Josh Humphrey/Arizona_State/80/304/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Michael Petit/Texas_AM/75/322/Pass Blocking/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Rick Veney/Tulsa/76/293/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Cody Dowdell/Virginia_Tech/77/338/Run Blocking/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("T/Chuck Weaver/Colorado/74/344/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Tez Mackey/UTSA/78/333/Run Blocking/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Terrance Smith/ECU/78/307/Pass Blocking/Great/21"));
            players.Add(PlayerFactory.GeneratePlayer("G/Travis Mirvil/Nebraska/77/298/Run Blocking/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Andrew Simmons/Washington/76/287/Run Blocking/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Darren Campbell/Stanford/76/319/Pass Blocking/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Brad Huff/Marshall/76/279/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Allen Christensen/Notre_Dame/73/335/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Eric Rogers/Penn_State/77/315/Run Blocking/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Kevin Morgan/Vanderbilt/73/276/Run Blocking/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Jarrett Moore/Marshall/74/278/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Eric Bailey/LSU/74/301/Run Blocking/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Marques Hicks/Oklahoma/74/298/Pass Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Stephen King/Texas/76/362/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/J.J. Jones/Ole_Miss/76/338/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Steve Poland/Mississippi_State/75/302/Run Blocking/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Brian Swain/Ohio_State/73/305/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Trent Williams/Oklahoma/74/299/Run Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Bryan Carter/Texas_AM/77/288/Run Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Geoffrey Berg/Georgia/76/306/Pass Blocking/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Marcus Castillo/Iowa/76/305/Pass Blocking/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Ricky Culp/Navy/76/312/Pass Blocking/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("G/Wendell Francis/Tennessee/74/279/Balanced/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("G/Dwayne Rouse/BYU/73/304/Run Blocking/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("C/Tommy McNeal/Alabama/73/302/Pass Blocking/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Jerome Harris/Arkansas/73/293/Run Blocking/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("C/Gene Clarke/Texas_AM/72/302/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Will Lamb/Auburn/76/293/Pass Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Brandon Allen/Oklahoma/75/307/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("C/Mark Garrett/UCLA/76/310/Run Blocking/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Brad Collier/Tennessee/73/322/Pass Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Michael Johnson/Arkansas_State/76/290/Pass Blocking/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Sterling Heinz/Virginia_Tech/72/292/Pass Blocking/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("C/Gabriel Williams/Arkansas/77/342/Pass Blocking/Random/23"));
            players.Add(PlayerFactory.GeneratePlayer("K/Chris Skinner/Miami_OH/71/224/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("K/Nick Nichols/Texas/73/179/Power/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("K/Clint Rutledge/Texas_AM/70/187/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("K/Eric Busch/Illinois/72/200/Accurate/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("P/Early Carter/Western_Michigan/73/215/Accurate/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("P/Jermaine Chandler/Iowa/73/221/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("P/Adam Fine/Marshall/75/207/Power/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("P/C.J. Collins/Nebraska/70/222/Accurate/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Will Hagen/Marshall/74/245/Pass Rusher/Generational/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Daniel Oliver/UTSA/76/264/Balanced/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Andrew Allen/Texas_AM/75/280/Run Stopper/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Jason Cooper/Alabama/75/243/Pass Rusher/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Rob Dailey/Auburn/74/274/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Cedric Williams/Michigan/77/259/Run Stopper/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Adam Gunn/LSU/78/270/Run Stopper/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Darren Roberts/Alabama/77/267/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Mike Hill/Clemson/75/292/Run Stopper/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/John Murray/Oklahoma/73/249/Pass Rusher/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Mike Brooks/Georgia/78/248/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Wayne Mitchell/Penn_State/75/290/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Larry Richardson/Washington/74/369/Pass Rusher/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Scott Keenan/Texas/75/252/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Michael Mackey/Arkansas/77/256/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Joseph Stone/Virginia_Tech/74/265/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Andrew Bowie/Michigan_State/72/238/Run Stopper/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Charles Thomas/Florida_State/78/283/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Willie McDaniel/Middle_Tennessee/79/259/Run Stopper/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Zach Darby/San_Diego_State/74/259/Pass Rusher/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/William Scott/Cal/73/267/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Demetrius Adams/Florida/77/259/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Donnie Mason/Kentucky/78/257/Run Stopper/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Jeff Cooper/Michigan_State/75/252/Pass Rusher/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/William O'Brien/Arizona/77/277/Run Stopper/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Michael Means/Kentucky/75/278/Run Stopper/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("DE/Jeremy Hollis/UConn/75/264/Run Stopper/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Darren Swan/ECU/74/267/Run Stopper/Great/21"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Jason Miller/Ohio_State/76/317/Balanced/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Donte Jones/Tennessee/75/264/Pass Rusher/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Paul Pollard/South_Carolina/75/288/Run Stopper/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Brent Coleman/South_Carolina/75/278/Run Stopper/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Steve Holmes/Nebraska/73/283/Pass Rusher/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Bo Burnette/Oklahoma/74/340/Pass Rusher/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Marcus Owens/LSU/78/267/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Jose Fuqua/Nebraska/76/301/Run Stopper/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Richard Jones/NC_State/74/274/Run Stopper/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Joe Upshaw/Auburn/76/287/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Scott Poe/Minnesota/74/283/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/John Griffin/Michigan/73/271/Pass Rusher/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Danny Patton/South_Carolina/76/306/Run Stopper/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Isaiah Elliott/Mississippi_State/77/297/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Pierre Morgan/Boston_College/74/302/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Adam Hart/Minnesota/75/294/Run Stopper/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Chris Rawls/Syracuse/75/291/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Eddie Harris/Rutgers/75/277/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("DT/Cameron Banks/Oregon_State/75/269/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Larry Rutledge/Alabama/75/259/Run Stopper/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Joe Johnson/Georgia/75/240/Run Stopper/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Danny Robinson/Oklahoma/74/236/Pass Rusher/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Michael Stewart/Oklahoma/73/222/Coverage/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/William Thomas/Ole_Miss/74/234/Coverage/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Quintin Manning/Kentucky/77/233/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Josh Adams/Washington/74/219/Pass Rusher/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Nate Bean/Pitt/72/210/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Clifford Myrick/Baylor/73/236/Run Stopper/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Matt Thompson/Arizona_State/73/222/Run Stopper/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Chris Baker/Arkansas/72/222/Pass Rusher/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Pat Foster/Texas/72/227/Run Stopper/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Chris Robinson/Texas_Tech/75/243/Pass Rusher/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Luke James/Michigan_State/78/237/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/David Meeks/Nevada/74/233/Coverage/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Clifton Thomas/Auburn/74/239/Pass Rusher/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Paul Jean/Oregon/74/240/Pass Rusher/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Donald Boyd/Syracuse/74/252/Run Stopper/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Pat Nichols/West_Virginia/77/232/Run Stopper/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Tim Estes/Colorado/74/236/Run Stopper/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Jordan Humphrey/Fresno_State/73/232/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("OLB/Lamar Sharpe/Virginia/72/209/Coverage/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Cedric Davis/Alabama/73/220/Balanced/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Marcus Houston/Texas/70/246/Balanced/Great/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/David Martinez/Texas_AM/74/238/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Luke Cunningham/Alabama/72/251/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Chris Tucker/Oklahoma/73/238/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Tim Christian/Tennessee/71/239/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Terrence Yancey/LSU/70/247/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Ryan Bentley/Michigan/71/251/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Nick Marshall/Nebraska/72/223/Coverage/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Cornelius Miller/Ohio_State/73/247/Run Stopper/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Brad Franklin/Notre_Dame/74/245/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Trey Quinn/Stanford/73/230/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Derrick Gunn/Mississippi_State/71/234/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Tim Wilson/Ole_Miss/76/236/Coverage/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Charlie Clifford/Colorado_State/75/233/Run Stopper/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Courtney McNeil/TCU/73/251/Coverage/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Nate Fry/Texas_AM/72/225/Coverage/Random/23"));
            players.Add(PlayerFactory.GeneratePlayer("MLB/Kenny Butler/Oklahoma/73/238/Coverage/Random/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB&QB/Lenny Swain/Marshall/75/200/Balanced/Generational/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Chris Hunter/Ohio/73/174/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/James Brooks/Notre_Dame/71/170/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Andrew Vinson/Texas_AM/73/210/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Landon Watson/West_Virginia/71/185/Hard Hitter/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Adam Kelly/Florida/71/180/Zone/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Drew Jackson/Alabama/72/192/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Zach Alexander/SMU/72/191/Hard Hitter/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Stephen Conley/Miami_FL/73/183/Hard Hitter/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Joe Huston/Alabama/73/183/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Kyle Ashley/Oregon/72/192/Man/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Lui James/Washington/73/185/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Brandon Vaughn/Kansas_State/71/211/Hard Hitter/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Chad Weisbecker/Marshall/71/185/Balanced/Average/21"));
            players.Add(PlayerFactory.GeneratePlayer("CB/James White/Oregon/72/172/Zone/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Alex Smith/South_Carolina/73/198/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Rondell Foster/ECU/72/174/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Cliff McDonald/Tennessee/71/173/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Tim Smith/Clemson/72/192/Zone/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Geoff Riley/Florida_State/71/182/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Richard Brown/Louisville/72/181/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Jonathan Harrison/Miami_FL/70/187/Hard Hitter/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Charles Williams/Ole_Miss/71/195/Zone/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Tim Wright/Penn_State/72/180/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/David Sims/Texas/70/194/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Albert Battle/Arkansas/72/229/Hard Hitter/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Brad Holmes/ECU/73/183/Balanced/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Matt Brady/Georgia_Tech/74/185/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Ed Graves/Hawaii/71/189/Zone/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Josh Todd/NC_State/70/196/Hard Hitter/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Kyle Lewis/Northern_Illinois/72/183/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("CB/Charles Peterson/Rice/71/186/Balanced/Awful/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Antonio Weaver/Marshall/72/221/Coverage/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Seth Harrison/Alabama/72/198/Hard Hitter/Great/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Matt Jackson/Notre_Dame/72/208/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Kevin Smith/Tennessee/73/216/Hard Hitter/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Joe Bradshaw/Michigan/71/179/Balanced/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Craig Cruz/Marshall/71/194/Coverage/Good/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/John Smith/Oklahoma/72/208/Balanced/Good/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Bill Noble/Missouri/73/188/Hard Hitter/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Todd Neal/Maryland/73/208/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/John Monroe/Florida_State/72/175/Coverage/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/John Hill/Akron/74/218/Hard Hitter/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Quinton Davis/Wisconsin/71/203/Balanced/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Skyler Watson/North_Carolina/75/181/Coverage/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Jason Jones/Michigan_State/72/182/Coverage/Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/M.J. McBride/Oregon/75/206/Balanced/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Patrick Howard/Houston/73/189/Coverage/Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Jeremy James/Boise_State/73/191/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Geremy Hill/Wisconsin/73/186/Balanced/Below Average/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Joe Paris/Louisiana_Tech/73/195/Coverage/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Alex Thompson/Miami_FL/75/217/Balanced/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Dan Maxwell/South_Carolina/73/218/Coverage/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Kenny Bell/UTEP/71/190/Hard Hitter/Below Average/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Brenton Meade/Western_Kentucky/74/201/Coverage/Bad/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Adam Price/Georgia_Tech/72/184/Balanced/Bad/23"));
            players.Add(PlayerFactory.GeneratePlayer("S/Mike Swanson/Navy/73/221/Coverage/Awful/22"));
            players.Add(PlayerFactory.GeneratePlayer("S/Chris Hines/Nebraska/73/198/Balanced/Awful/23"));
            return players;
        }
    }

}
